version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - REGISTRY_CACHE_DIR=cache
    ports:
      - "5000:5000"
    volumes:
      - ./cache:/cache:rw
